server:
  port: 8080

spring:
  application:
    name: accounts-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  pattern:
    console: "%green(%d{yyyy-MM-dd HH:mm:ss.SSS}) %blue(%-5level) %magenta(${PID:- }) --- %red([%15.15thread]) %yellow(%-40.40logger{39}): %msg%n%wEx"

build:
  version: 2.0

accounts:
  message: Welcome to Accounts service
  contactDetails:
    name: Tom - Developer
    email: tom@gmail.com
  onCallSupport:
    - (000) 123-4567
    - (000) 234-5678