build:
  version: prod-2.0

accounts:
  message: Welcome to prod Accounts service
  contactDetails:
    name: May - Product Owner
    email: may@gmail.com
  onCallSupport:
    - (000) 111-2222
    - (000) 222-3333